platform :ios, '13.2'
use_frameworks!

target 'BothSidesCamera_Example' do
  pod 'BothSidesCamera', :path => '../'

  target 'BothSidesCamera_Tests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end
end
